implemented stop|restart|reload|force-reload in init scripts to fix lintian warnings; removed trailing spaces

diff --git a/etc/init.d/tails-reconfigure-kexec b/etc/init.d/tails-reconfigure-kexec
--- a/etc/init.d/tails-reconfigure-kexec
+++ b/etc/init.d/tails-reconfigure-kexec
@@ -2,9 +2,9 @@
 ### BEGIN INIT INFO
 # Provides:		tails-reconfigure-kexec
 # Required-Start:	$local_fs
-# Required-Stop:	
+# Required-Stop:
 # Default-Start:        2 3 4 5
-# Default-Stop:		
+# Default-Stop:
 # Short-Description:    Reconfigure kexec depending on running kernel
 # Description:          Reconfigure kexec depending on running kernel
 ### END INIT INFO
@@ -23,6 +23,10 @@ case "$1" in
 	else
 	   echo 'APPEND="${APPEND} quiet"'        >> "$KEXEC_CONF"
 	fi
+	;;
+  stop|restart|reload|force-reload)
+	echo "Error: argument '$1' not supported" >&2
+	exit 3
 	;;
   *)
 	echo "Usage: $0 start" >&2
diff --git a/etc/init.d/tails-reconfigure-memlockd b/etc/init.d/tails-reconfigure-memlockd
--- a/etc/init.d/tails-reconfigure-memlockd
+++ b/etc/init.d/tails-reconfigure-memlockd
@@ -2,9 +2,9 @@
 ### BEGIN INIT INFO
 # Provides:		tails-reconfigure-memlockd
 # Required-Start:	$local_fs
-# Required-Stop:	
+# Required-Stop:
 # Default-Start:        2 3 4 5
-# Default-Stop:		
+# Default-Stop:
 # X-Start-Before:       memlockd
 # Short-Description:    Reconfigure memlockd depending on running kernel
 # Description:          Reconfigure memlockd depending on running kernel
@@ -26,6 +26,10 @@ case "$1" in
 	mkdir -p /lib/init/rw/sendsigs.omit.d
 	rm -f /lib/init/rw/sendsigs.omit.d/memlockd
 	ln -s /var/run/memlockd.pid /lib/init/rw/sendsigs.omit.d/memlockd
+	;;
+  stop|restart|reload|force-reload)
+	echo "Error: argument '$1' not supported" >&2
+	exit 3
 	;;
   *)
 	echo "Usage: $0 start" >&2
